version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    environment:
      CODECOV_TOKEN: 70be8a3a-e0d9-42f3-9716-918ad198cbc1
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test:unit
      - run: npm run build
      - run: npx codecov

workflows:
  version: 2
  run_test:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
